blueprint:
  name: Two Switch Light Control
  description: Control one light with two switches supporting single, double, and long-press actions.
  domain: automation
  input:
    switch1_entity:
      name: First Switch Entity
      description: The first switch entity.
      selector:
        entity:
          domain: switch
    switch2_entity:
      name: Second Switch Entity
      description: The second switch entity.
      selector:
        entity:
          domain: switch
    full_light_entity:
      name: Full Light Entity
      description: The light entity for full light mode.
      selector:
        entity:
          domain: light
    night_light_entity:
      name: Night Light Entity
      description: The light entity for night light mode.
      selector:
        entity:
          domain: light
    ambient_light_entity:
      name: Ambient Light Entity
      description: The light entity for ambient light mode.
      selector:
        entity:
          domain: light

mode: parallel

trigger:
  - platform: state
    entity_id: !input switch1_entity
  - platform: state
    entity_id: !input switch2_entity

variables:
  click_type: "{{ trigger.to_state.attributes.click_type }}"
  button_id: "{{ 'switch1' if trigger.entity_id == input.switch1_entity else 'switch2' }}"
  full_light_target: "{{ input.full_light_entity }}"
  night_light_target: "{{ input.night_light_entity }}"
  ambient_light_target: "{{ input.ambient_light_entity }}"

action:
  - choose:
      - conditions:
          - "{{ click_type == 'single' }}"
          - "{{ button_id == 'switch1' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input night_light_entity

      - conditions:
          - "{{ click_type == 'double' }}"
          - "{{ button_id == 'switch1' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input full_light_entity

      - conditions:
          - "{{ click_type == 'long' }}"
          - "{{ button_id == 'switch1' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input ambient_light_entity

      - conditions:
          - "{{ click_type == 'single' }}"
          - "{{ button_id == 'switch2' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input night_light_entity

      - conditions:
          - "{{ click_type == 'double' }}"
          - "{{ button_id == 'switch2' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input full_light_entity

      - conditions:
          - "{{ click_type == 'long' }}"
          - "{{ button_id == 'switch2' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input ambient_light_entity

