blueprint:
  name: Zigbee Button Light Control
  description: Control different light entities with Zigbee buttons supporting single, double, and long-press actions.
  domain: automation
  input:
    button1_entity:
      name: First Zigbee Button Entity
      description: The entity ID of the first Zigbee button.
      selector:
        entity:
          domain: binary_sensor
    button2_entity:
      name: Second Zigbee Button Entity
      description: The entity ID of the second Zigbee button.
      selector:
        entity:
          domain: binary_sensor
    full_light_entity:
      name: Full Light Entity
      description: The entity ID of the light for full light mode.
      selector:
        entity:
          domain: light
    night_light_entity:
      name: Night Light Entity
      description: The entity ID of the light for night light mode.
      selector:
        entity:
          domain: light
    ambient_light_entity:
      name: Ambient Light Entity
      description: The entity ID of the light for ambient light mode.
      selector:
        entity:
          domain: light

mode: parallel

trigger:
  - platform: state
    entity_id: !input button1_entity
  - platform: state
    entity_id: !input button2_entity

variables:
  click_type: "{{ trigger.to_state.state }}"
  button_id: "{{ 'button1' if trigger.entity_id == input.button1_entity else 'button2' }}"
  full_light_target: "{{ input.full_light_entity }}"
  night_light_target: "{{ input.night_light_entity }}"
  ambient_light_target: "{{ input.ambient_light_entity }}"

action:
  - choose:
      - conditions:
          - "{{ click_type == 'single' }}"
          - "{{ button_id == 'button1' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input night_light_entity

      - conditions:
          - "{{ click_type == 'double' }}"
          - "{{ button_id == 'button1' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input full_light_entity

      - conditions:
          - "{{ click_type == 'long' }}"
          - "{{ button_id == 'button1' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input ambient_light_entity

      - conditions:
          - "{{ click_type == 'single' }}"
          - "{{ button_id == 'button2' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input night_light_entity

      - conditions:
          - "{{ click_type == 'double' }}"
          - "{{ button_id == 'button2' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input full_light_entity

      - conditions:
          - "{{ click_type == 'long' }}"
          - "{{ button_id == 'button2' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: !input ambient_light_entity


